### ISSUE TITLE
Som en användare vill jag kunna se en lista av mina dagliga sysslor så jag vet vad jag ska göra.

### ISSUE THREAD

**Issue by LinusIlbratt** [LinusIlbratt/TaskManager#14]
Krav lista
- Visa dagens och veckans dagar på ett enkelt sätt för användaren
- Ladda ner dagens sysslor till en lista för användaren att ha koll på
- en knapp så att användaren kan klicka så en syssla är klar

**Comment by mattias012** [comment]
Marked as done

**Comment by mattias012** [comment]
All details from Figma template implemented, marked as closed.
