### ISSUE TITLE
Som en användare vill jag kunna boka professionella städare genom appen så att jag kan få extra hjälp när jag behöver det.

### ISSUE THREAD

**Issue by LinusIlbratt** [LinusIlbratt/TaskManager#37]

**Comment by LinusIlbratt** [comment]
Som en användare vill jag kunna se en lista över de städtjänster som företaget erbjuder så att jag kan välja en tjänst som passar mina behov.

Som en användare vill jag kunna se en lista över tillgängliga städare från företaget med grundläggande information (namn, betyg, specialitet) så att jag kan välja en städare som passar mig. (här kan vi ju använda oss själva som städare?)

Som en användare vill jag kunna se information om varje städtjänst inklusive pris och vad som ingår så att jag kan fatta ett informerat beslut.

Som en användare vill jag kunna välja datum och tid för städningen baserat på städarens tillgänglighet så att jag kan boka en tid som passar mig.

Som en användare vill jag få en bekräftelse på min bokning via e-post och/eller appens notifikationer så att jag vet att bokningen är bekräftad.

Som en användare vill jag kunna se mina kommande bokningar i en kalender eller lista så att jag kan hålla koll på när städningarna ska ske.

**Comment by LinusIlbratt** [comment]
Skapa ett formulär för användarna för att ansöka om städ/service hjälp.

**Comment by mattias012** [comment]
This is done?
